--- #YAML:1.0
name:               Chemistry-Harmonia
version:            0.08
abstract:           Decision of simple and difficult chemical puzzles.
author:
    - Alessandro Gorohovski <angel@domashka.kiev.ua>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Algorithm::Combinatorics:  0.26
    Carp:                 0
    Chemistry::File::Formula:  0.37
    Math::Assistant:      0.04
    Math::BigInt:         1.997
    Math::BigRat:         0.2602
    Regexp::Common:       2011041701
    String::CRC::Cksum:   0.91
    Test::LongString:     0.15
    Test::More:           0.98
    Test::Pod:            1.45
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
